// Public, origin-restricted browser key. Private account credentials are never included.
const ADDRESS_CONFIG={provider:'geoapify',key:'dc9a4cddc5e14b598cc89d447aeb26f2'};
function normalizeAddressCity(value){return (value||'').replace(/^Village of\s+/i,'')}
let addressBiasPromise,deviceBias='';try{deviceBias=sessionStorage.getItem('chagDeviceBias')||''}catch(e){}
function setDeviceBias(lon,lat){deviceBias='proximity:'+lon.toFixed(4)+','+lat.toFixed(4);try{sessionStorage.setItem('chagDeviceBias',deviceBias)}catch(e){}}
function askDeviceLocation(){return new Promise((ok,no)=>navigator.geolocation.getCurrentPosition(p=>{setDeviceBias(p.coords.longitude,p.coords.latitude);ok()},no,{timeout:10000,maximumAge:600000}))}
if(navigator.permissions&&navigator.geolocation)navigator.permissions.query({name:'geolocation'}).then(r=>{if(r.state==='granted'&&!deviceBias)askDeviceLocation().catch(()=>{})}).catch(()=>{});
function getAddressBias(){if(deviceBias)return Promise.resolve(deviceBias);if(!addressBiasPromise)addressBiasPromise=(async()=>{try{const response=await fetch('https://api.geoapify.com/v1/ipinfo?apiKey='+encodeURIComponent(ADDRESS_CONFIG.key),{signal:AbortSignal.timeout(3000)});if(!response.ok)return '';const data=await response.json();const lon=data.location?.longitude,lat=data.location?.latitude;return Number.isFinite(lon)&&Number.isFinite(lat)?'proximity:'+lon+','+lat:''}catch(e){return ''}})();return addressBiasPromise}
const ADDRESS_PROVIDERS={geoapify:async(text,signal)=>{const bias=await getAddressBias();if(signal.aborted)throw new DOMException('Aborted','AbortError');const url=new URL('https://api.geoapify.com/v1/geocode/autocomplete');Object.entries({text,filter:'countrycode:us',limit:5,format:'json',apiKey:ADDRESS_CONFIG.key}).forEach(([k,v])=>url.searchParams.set(k,v));if(bias)url.searchParams.set('bias',bias);const res=await fetch(url,{signal});if(!res.ok)throw new Error('Address suggestions unavailable');const data=await res.json();return (data.results||[]).map(p=>({label:(p.formatted||'').replace(/(^|,\s*)Village of\s+/gi,'$1'),street:[p.housenumber,p.street].filter(Boolean).join(' ')||p.address_line1||'',city:normalizeAddressCity(p.city||p.town||p.village||''),state:p.state_code||p.state||'',zip:p.postcode||''}))}};
function attachAddressAutocomplete(ids){const street=document.getElementById(ids.street);if(!street)return;street.setAttribute('role','combobox');street.setAttribute('aria-autocomplete','list');street.setAttribute('aria-expanded','false');const results=document.createElement('div');results.className='address-results';results.id=ids.street+'-results';results.setAttribute('role','listbox');street.setAttribute('aria-controls',results.id);street.parentNode.classList.add('address-anchor');street.insertAdjacentElement('afterend',results);let timer,controller,items=[],active=-1;const close=()=>{results.replaceChildren();items=[];active=-1;street.setAttribute('aria-expanded','false')};const choose=i=>{const item=items[i];if(!item)return;street.value=item.street;['city','state','zip'].forEach(k=>{const input=document.getElementById(ids[k]);if(input&&item[k])input.value=item[k]});close();document.getElementById(ids.city)?.focus()};street.addEventListener('input',()=>{clearTimeout(timer);controller?.abort();close();const text=street.value.trim();if(text.length<3)return;timer=setTimeout(async()=>{controller=new AbortController();try{const values=await ADDRESS_PROVIDERS[ADDRESS_CONFIG.provider](text,controller.signal);if(street.value.trim()!==text)return;items=values;results.replaceChildren();items.forEach((item,i)=>{const button=document.createElement('button');button.type='button';button.className='address-option';button.setAttribute('role','option');button.id=results.id+'-'+i;button.tabIndex=-1;button.textContent=item.label;button.addEventListener('click',()=>choose(i));results.append(button)});if(items.length){const credit=document.createElement('div');credit.className='dropdown-credit';credit.innerHTML='<a href="https://www.geoapify.com/" target="_blank" rel="noopener">Geoapify</a> | <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a>';results.append(credit)}street.setAttribute('aria-expanded',String(items.length>0))}catch(e){if(e.name!=='AbortError')close()}},400)});street.addEventListener('keydown',e=>{if(e.key==='Escape'){close();return}if(!items.length)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();active=(active+(e.key==='ArrowDown'?1:-1)+items.length)%items.length;[...results.querySelectorAll('.address-option')].forEach((el,i)=>el.classList.toggle('selected',i===active));street.setAttribute('aria-activedescendant',results.children[active].id)}if(e.key==='Enter'&&active>=0){e.preventDefault();choose(active)}});street.addEventListener('blur',()=>setTimeout(close,150))}
attachAddressAutocomplete({street:'street',city:'city',state:'state',zip:'zip'});
attachAddressAutocomplete({street:'billstreet',city:'billcity',state:'billstate',zip:'billzip'});
